/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedScannerIndexRouteImport } from './routes/_authenticated/scanner/index'
import { Route as AuthenticatedProdutosIndexRouteImport } from './routes/_authenticated/produtos/index'
import { Route as AuthenticatedMovimentacoesIndexRouteImport } from './routes/_authenticated/movimentacoes/index'
import { Route as AuthenticatedEquipesIndexRouteImport } from './routes/_authenticated/equipes/index'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes/index'

const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScannerIndexRoute =
  AuthenticatedScannerIndexRouteImport.update({
    id: '/scanner/',
    path: '/scanner/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProdutosIndexRoute =
  AuthenticatedProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMovimentacoesIndexRoute =
  AuthenticatedMovimentacoesIndexRouteImport.update({
    id: '/movimentacoes/',
    path: '/movimentacoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipesIndexRoute =
  AuthenticatedEquipesIndexRouteImport.update({
    id: '/equipes/',
    path: '/equipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/entrar': typeof EntrarRoute
  '/': typeof AuthenticatedIndexRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/equipes': typeof AuthenticatedEquipesIndexRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
  '/scanner': typeof AuthenticatedScannerIndexRoute
}
export interface FileRoutesByTo {
  '/entrar': typeof EntrarRoute
  '/': typeof AuthenticatedIndexRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/equipes': typeof AuthenticatedEquipesIndexRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
  '/scanner': typeof AuthenticatedScannerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/equipes/': typeof AuthenticatedEquipesIndexRoute
  '/_authenticated/movimentacoes/': typeof AuthenticatedMovimentacoesIndexRoute
  '/_authenticated/produtos/': typeof AuthenticatedProdutosIndexRoute
  '/_authenticated/scanner/': typeof AuthenticatedScannerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/entrar'
    | '/'
    | '/configuracoes'
    | '/equipes'
    | '/movimentacoes'
    | '/produtos'
    | '/scanner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/entrar'
    | '/'
    | '/configuracoes'
    | '/equipes'
    | '/movimentacoes'
    | '/produtos'
    | '/scanner'
  id:
    | '__root__'
    | '/_authenticated'
    | '/entrar'
    | '/_authenticated/'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/equipes/'
    | '/_authenticated/movimentacoes/'
    | '/_authenticated/produtos/'
    | '/_authenticated/scanner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EntrarRoute: typeof EntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner/': {
      id: '/_authenticated/scanner/'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos/': {
      id: '/_authenticated/produtos/'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movimentacoes/': {
      id: '/_authenticated/movimentacoes/'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipes/': {
      id: '/_authenticated/equipes/'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof AuthenticatedEquipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
  AuthenticatedEquipesIndexRoute: typeof AuthenticatedEquipesIndexRoute
  AuthenticatedMovimentacoesIndexRoute: typeof AuthenticatedMovimentacoesIndexRoute
  AuthenticatedProdutosIndexRoute: typeof AuthenticatedProdutosIndexRoute
  AuthenticatedScannerIndexRoute: typeof AuthenticatedScannerIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  AuthenticatedEquipesIndexRoute: AuthenticatedEquipesIndexRoute,
  AuthenticatedMovimentacoesIndexRoute: AuthenticatedMovimentacoesIndexRoute,
  AuthenticatedProdutosIndexRoute: AuthenticatedProdutosIndexRoute,
  AuthenticatedScannerIndexRoute: AuthenticatedScannerIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EntrarRoute: EntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
