/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProdutosIndexRouteImport } from './routes/_authenticated/produtos/index'
import { Route as AuthenticatedMovimentacoesIndexRouteImport } from './routes/_authenticated/movimentacoes/index'

const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProdutosIndexRoute =
  AuthenticatedProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMovimentacoesIndexRoute =
  AuthenticatedMovimentacoesIndexRouteImport.update({
    id: '/movimentacoes/',
    path: '/movimentacoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/entrar': typeof EntrarRoute
  '/': typeof AuthenticatedIndexRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/entrar': typeof EntrarRoute
  '/': typeof AuthenticatedIndexRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesIndexRoute
  '/produtos': typeof AuthenticatedProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/movimentacoes/': typeof AuthenticatedMovimentacoesIndexRoute
  '/_authenticated/produtos/': typeof AuthenticatedProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/entrar' | '/' | '/movimentacoes' | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to: '/entrar' | '/' | '/movimentacoes' | '/produtos'
  id:
    | '__root__'
    | '/_authenticated'
    | '/entrar'
    | '/_authenticated/'
    | '/_authenticated/movimentacoes/'
    | '/_authenticated/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EntrarRoute: typeof EntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos/': {
      id: '/_authenticated/produtos/'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movimentacoes/': {
      id: '/_authenticated/movimentacoes/'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMovimentacoesIndexRoute: typeof AuthenticatedMovimentacoesIndexRoute
  AuthenticatedProdutosIndexRoute: typeof AuthenticatedProdutosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMovimentacoesIndexRoute: AuthenticatedMovimentacoesIndexRoute,
  AuthenticatedProdutosIndexRoute: AuthenticatedProdutosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EntrarRoute: EntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
